### ISSUE TITLE
Multiple input

### ISSUE THREAD

**Issue by li-fang** [TencentYoutuResearch/3DFaceReconstruction-LAP#4]
Hi Zhang! Thanks for sharing your great work! Would you please provide the demo of multi input reconstruction? Also, the reconstructions of Asian faces looked not lifelike. Maybe because of the training dataset. So do you have plan to release the training code?

**Comment by JesseZhang92** [comment]
Hi，thanks for your interest to our work. We will release the training code later. Right now for multi-input condition, you can concatenate images along channel dimension and feed them to netA and netD, and set rand_inner_batch as the number of images. The target image should be fed into refine_netA and refine_netD. 

For the issue on Asian faces, it is due to the bias of training dataset. The released model is fine-tuned on CelebAMask-HQ dataset in which most identities are non-Asian. You may fine-tune the model on custom dataset. For the training losses and implementation, you may refer to [unsup3D](https://github.com/elliottwu/unsup3d).
